freebsd_instance:
  image_family: freebsd-14-0-snap

task:
  env:
    # LAN configuration
    lan_ifconfig: "inet 10.0.0.2/24"
    lan_defaultrouter: "10.0.0.1"

    # WAN configuration
    wan_ifconfig: "inet 192.0.2.1/30"

    # Firewall configuration
    firewall_ifconfig_wan_name: em0
    firewall_ifconfig_lan_name: em1

  setup_script:
    - sh .setup/setup.sh

  tests_script:
    - sh tests/*.sh
