freebsd_instance:
  image_family: freebsd-14-0-snap

task:
  env:
    inside_ifconfig_if0: "inet 10.0.0.2/24"
    inside_defaultrouter: "10.0.0.1"

  script:
    - kldload pf
    - outa=$(ifconfig epair create)
    - out=${outa%a}
    - ina=$(ifconfig epair create)
    - in=${ina%a}
    - jail -c name=firewall persist vnet vnet.interface=${out}a vnet.interface=${in}a
    - jail -c name=outside persist vnet vnet.interface=${out}b
    - jail -c name=inside persist vnet vnet.interface=${in}b
    - jexec outside ifconfig ${out}b inet 192.0.2.1/24
    - jexec firewall ifconfig ${out}a inet 192.0.2.2/24
    - jexec firewall ifconfig ${in}a inet 10.0.0.1/24
    - jexec firewall sysctl net.inet.ip.forwarding=1
    - jexec firewall pfctl -f ${CIRRUS_WORKING_DIR}/pf.conf
    - jexec inside ifconfig ${in}b ${inside_ifconfig_if0}
    - jexec inside route add default ${inside_defaultrouter}
    - jexec outside route add default 192.0.2.2
    - jexec inside ping -c 3 192.0.2.1
    - jexec firewall pfctl -s all
    - jexec outside ping -c 3 10.0.0.2 || true
