freebsd_instance:
  image_family: freebsd-14-0-snap

env:
  # LAN configuration
  lan_ifconfig: "inet 192.168.1.2/24"
  lan_defaultrouter: 192.168.1.1

  # DMZ configuration
  dmz_ifconfig: "inet 192.168.2.2/24"
  dmz_defaultrouter: 192.168.2.1

  # WAN configuration
  wan_ifconfig: "inet 192.0.2.1/30"

  # Firewall configuration
  firewall_ifconfig_wan: "inet 192.0.2.2/30"
  firewall_ifconfig_lan: "inet 192.168.1.1/24"
  firewall_ifconfig_dmz: "inet 192.168.2.1/24"
  firewall_ifconfig_wan_name: octe0
  firewall_ifconfig_lan_name: octe1
  firewall_ifconfig_dmz_name: octe2

task:
  setup_script:
    - sh .setup/setup.sh

  tcpdump_wan_background_script: jexec firewall tcpdump -ennlSvvXX -i ${firewall_ifconfig_wan_name}
  tcpdump_lan_background_script: jexec firewall tcpdump -ennlSvvXX -i ${firewall_ifconfig_lan_name}
  tcpdump_dmz_background_script: jexec firewall tcpdump -ennlSvvXX -i ${firewall_ifconfig_dmz_name}
  pflog_background_script: jexec firewall tcpdump -n -e -ttt -i pflog0

  # XXX Figure out if Cirrus has a matrix similar to GitHub Actions to avoid repetition
  test_nat_outgoing_traffic_script:
    - sh tests/nat_outgoing_traffic.sh
    - sleep 2 # XXX wait a whie before teardown

  test_reject_anything_with_spoofed_addresses_script:
    - sh tests/reject_anything_with_spoofed_addresses.sh
    - sleep 2 # XXX wait a whie before teardown

  test_allow_lan_to_ping_us_script:
    - sh tests/allow_lan_to_ping_us.sh
    - sleep 2 # XXX wait a whie before teardown
